services:

  gateway:
    image: zaranik/grid-gateway:latest
    ports:
      - "80:8080"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
    restart: always

  note-chat-service:
    image: zaranik/grid-note-chat-service:latest
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always
    depends_on:
      - note-mcp-server

  note-mcp-server:
    image: zaranik/grid-note-mcp-server:latest
    restart: always
    
  notes-service:
    image: nelepindmitriy/grid-lab-image
    environment:
      - MONGODB_URI=${MONGODB_URI}
    restart: always

  frontend:
    image: zaranik/grid_lab1_frontend:lab2
    restart: always
  
