services:
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - nodejs
  #     - react
  #   restart: always
  
  gateway:
    image: zaranik/grid-gateway:latest
    ports:
      - "80:8080"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
    restart: always
    
  notes-service:
    image: nelepindmitriy/grid-lab-image
    environment:
      - MONGODB_URI=${MONGODB_URI}
    restart: always

  frontend:
    image: zaranik/grid_lab1_frontend:lab2
    restart: always
  
